# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  rss-teams-webhook

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  # terraform.tfvars mapping
  TeamsWebhookUrl: # name_prefix
    Description: (Require) TeamsWebhookUrl
    Type: String
    # MinLength: 3
    # MaxLength: 50
    # AllowedPattern: ^[a-z][a-z0-9_]+$
  RssList:
    Description: (Require) RssList
    Type: String


# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs12.x
      Handler: src/index.handler
      # This property associates this Lambda function with a scheduled CloudWatch Event. For all available properties, see
      # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
      # This example runs every hour.
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          TEAMS_WEBHOOK_URL: !Sub ${TeamsWebhookUrl}
          TEAMS_WEBHOOK_LIMIT: 5 # https://docs.microsoft.com/ja-jp/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit
          RSS_LIST: !Sub ${RssList}
      MemorySize: 128
      Timeout: 100
