AWSTemplateFormatVersion: 2010-09-09
Description: >-
  rss-teams-webhook
Transform:
  - AWS::Serverless-2016-10-31
Parameters:
  TeamsWebhookUrl:
    Description: (Require) TeamsWebhookUrl
    Type: String
  RssList:
    Description: (Require) RssList
    Type: String
  ExecutionIntervalHour:
    Description: (Require) ExecutionIntervalHour
    Type: Number
    Default: 1
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: src/index.handler
      Policies:
        - TranslateReadOnly
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Sub rate(${ExecutionIntervalHour} hour)
      Environment:
        Variables:
          TEAMS_WEBHOOK_URL: !Sub ${TeamsWebhookUrl}
          # https://docs.microsoft.com/ja-jp/microsoftteams/platform/bots/how-to/rate-limit#per-bot-per-thread-limit
          TEAMS_WEBHOOK_LIMIT: 5
          RSS_LIST: !Sub ${RssList}
          EXECUTION_INTERVAL_HOUR: !Sub ${ExecutionIntervalHour}
      MemorySize: 512
      Timeout: 300
